### ISSUE TITLE
Error : Typed property App\Models\User::$name must not be accessed before initialization

### ISSUE THREAD

**Issue by milewski** [lepikhinb/laravel-fluent#5]
Hi, I have a very simple example like this:

```php
class User extends Model
{
    use Fluent;

    public string $name;
}
```

Within tests:

```php
$user = UserFactory::new()->create();
dd($user->name);
```

Throws an error:

```
Error : Typed property App\Models\User::$name must not be accessed before initialization
```

**Comment by lepikhinb** [comment]
What Laravel version is being used? I just tried the same example, and it worked as expected.

**Comment by devRMA** [comment]
I'm having the same problem.
Versions:
PHP: 8.0.10
laravel/framework: v8.61.0

**Comment by cbaconnier** [comment]
@milewski 

I can only reproduce this by setting `name` to `nullable` and removing the `name` from the factory. 
Do you have any other package that can conflict with this one? 
Perhaps, do you have a reproducible example?


@devRMA 

I can reproduce this one, but loading the relation instead of lazyloading works. 

```
$car2->load('user')->user;

// or
$car2  = \App\Models\Car::with('user')->find(1)
```

I think, this makes sense since `user` is not initialized at this moment and needs to be initialized at some point before you can actually call the property. But that just how PHP works. I'm unsure Fluent can be compatible with LazyLoading.

**Comment by milewski** [comment]
Uhm I was using this package https://github.com/spatie/data-transfer-object as well when this happened, I will try to hook up this library again on some other project and see if I can find out what is wrong

**Comment by lepikhinb** [comment]
@devRMA The package doesn't support lazy loading. Unfortunately, there's no way to overload public properties by magic getters and setters, so we can't access relations directly unless they're loaded explicitly.

**Comment by lepikhinb** [comment]
@milewski Let me know if the issue was resolved. Otherwise, I would love to see a more detailed example.

**Comment by devRMA** [comment]
> @devRMA The package doesn't support lazy loading. Unfortunately, there's no way to overload public properties by magic getters and setters, so we can't access relations directly unless they're loaded explicitly.

Thanks for the answer. I think this should be in the README, which only works with eager loading.

**Comment by lepikhinb** [comment]
@devRMA will note this on README. Thanks!

**Comment by Putr** [comment]
FYI @lepikhinb this was not noted on README.

It's a huge drawback as MyModel::find(1) is no longer a valid way of doing things.
